/**
 * 预设大模型供应商
 * protocol: 'openai'（OpenAI 兼容 chat/completions）| 'anthropic'（Messages 协议）| 'local'（内置引擎）
 * 模型名更新很快，这里给的是常用值，随时可以在输入框里改成任意模型。
 */
window.PROVIDERS = [
  {
    id: 'local',
    name: '内置引擎 · 离线（不用 Key，可直接玩）',
    protocol: 'local',
    baseUrl: '',
    model: 'gomoku-engine-v1',
    models: ['gomoku-engine-v1'],
    home: '',
    tip: '纯启发式引擎，反应最快，也用来做模型解析失败时的兜底。',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek 深度求索',
    protocol: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    model: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner', 'deepseek-v4-pro', 'deepseek-v4-flash'],
    home: 'https://platform.deepseek.com',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    protocol: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    model: 'gpt-4.1',
    models: ['gpt-5', 'gpt-4.1', 'gpt-4o', 'gpt-4o-mini', 'o4-mini'],
    home: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    protocol: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    model: 'claude-sonnet-5',
    models: ['claude-opus-5', 'claude-sonnet-5', 'claude-haiku-4-5', 'claude-fable-5'],
    home: 'https://console.anthropic.com',
  },
  {
    id: 'qwen',
    name: '阿里通义千问（百炼）',
    protocol: 'openai',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    model: 'qwen-plus',
    models: ['qwen3-max', 'qwen-plus', 'qwen-turbo', 'qwen-flash'],
    home: 'https://dashscope.console.aliyun.com',
  },
  {
    id: 'moonshot',
    name: '月之暗面 Kimi',
    protocol: 'openai',
    baseUrl: 'https://api.moonshot.cn/v1',
    model: 'kimi-k2.5',
    models: ['kimi-k2.5', 'kimi-k2-thinking', 'moonshot-v1-8k', 'moonshot-v1-32k'],
    home: 'https://platform.moonshot.cn',
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    protocol: 'openai',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    model: 'glm-4-plus',
    models: ['glm-4.6', 'glm-4-plus', 'glm-4-air', 'glm-4-flash'],
    home: 'https://open.bigmodel.cn',
  },
  {
    id: 'doubao',
    name: '火山方舟 · 豆包',
    protocol: 'openai',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    model: 'doubao-seed-2.0-pro',
    models: ['doubao-seed-2.0-pro', 'doubao-seed-2.0-lite', 'doubao-seed-2.0-mini'],
    home: 'https://console.volcengine.com/ark',
    tip: '豆包需要填「接入点 ID」（ep-xxxx）作为模型名。',
  },
  {
    id: 'hunyuan',
    name: '腾讯混元',
    protocol: 'openai',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    model: 'hunyuan-turbo',
    models: ['hunyuan-turbo', 'hunyuan-pro', 'hunyuan-standard'],
    home: 'https://cloud.tencent.com/product/hunyuan',
  },
  {
    id: 'gemini',
    name: 'Google Gemini（OpenAI 兼容端点）',
    protocol: 'openai',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    model: 'gemini-3-flash',
    models: ['gemini-3-pro', 'gemini-3-flash', 'gemini-2.5-flash'],
    home: 'https://aistudio.google.com/apikey',
    tip: '务必保留 URL 末尾的 /openai，并填写 Gemini 官方模型名。',
  },
  {
    id: 'grok',
    name: 'xAI Grok',
    protocol: 'openai',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-4',
    models: ['grok-4', 'grok-4-fast', 'grok-3-mini'],
    home: 'https://console.x.ai',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    protocol: 'openai',
    baseUrl: 'https://api.minimax.chat/v1',
    model: 'MiniMax-M2.5',
    models: ['MiniMax-M3', 'MiniMax-M2.5'],
    home: 'https://platform.minimaxi.com',
  },
  {
    id: 'siliconflow',
    name: '硅基流动 SiliconFlow（聚合）',
    protocol: 'openai',
    baseUrl: 'https://api.siliconflow.cn/v1',
    model: 'Qwen/Qwen3-32B',
    models: ['Qwen/Qwen3-32B', 'deepseek-ai/DeepSeek-V3', 'THUDM/GLM-4-9B-0414'],
    home: 'https://cloud.siliconflow.cn',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter（聚合，海外）',
    protocol: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    model: 'openai/gpt-4o',
    models: ['openai/gpt-4o', 'anthropic/claude-sonnet-4.6', 'google/gemini-2.5-pro', 'deepseek/deepseek-chat'],
    home: 'https://openrouter.ai/keys',
  },
  {
    id: 'ollama',
    name: 'Ollama / 本地自建（vLLM、LM Studio…）',
    protocol: 'openai',
    baseUrl: 'http://localhost:11434/v1',
    model: 'qwen2.5:7b',
    models: ['qwen2.5:7b', 'llama3.1', 'deepseek-r1:7b'],
    home: '',
    tip: 'Ollama 需设置 OLLAMA_ORIGINS=* 或经本服务转发；本机转发已由服务端处理。',
  },
  {
    id: 'custom',
    name: '自定义（OpenAI 兼容）',
    protocol: 'openai',
    baseUrl: '',
    model: '',
    models: [],
    home: '',
  },
];
